spring:
  application:
    name: journalApp
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: weekly-sentiment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.springboot.journalapp.model
            value:
              default:
                type: com.springboot.journalapp.model.SentimentData

  data:
    redis:
      url: ${REDIS_CONNECTION_URL}
    mongodb:
      uri: ${MONGODB_URI}/journaldb
      auto-index-creation: true
  config:
    import: optional:application-secret.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080